version: '2.0'

services:
  frontend:
    image: node:20
    command:
      - npm
      - run
      - start
    env:
      - PORT=80
      - HOST=0.0.0.0
      # Environment variables to connect to the other agentic services
      - SKETCH_TO_IMAGE_URL=http://sketch-to-image:8080
      - TEXT_TO_IMAGE_URL=http://text-to-image:8080
      - IMAGE_EDITOR_URL=http://image-editor:8080
    expose:
      - port: 80
        as: 80
        to:
          - global: true

  sketch-to-image:
    image: YOUR_DOCKERHUB_USERNAME/neon-canvanies-service:latest
    env:
      - HF_TOKEN=xxx
      - MODEL_ID=gokaygokay/Sketch-to-Image-Kontext-Dev-LoRA
    expose:
      - port: 8080
        to:
          - service: frontend

  text-to-image:
    image: YOUR_DOCKERHUB_USERNAME/neon-canvanies-service:latest
    env:
      - HF_TOKEN=xxx
      - MODEL_ID=lodestones/ChromaV2
    expose:
      - port: 8080
        to:
          - service: frontend

  image-editor:
    image: YOUR_DOCKERHUB_USERNAME/neon-canvanies-service:latest
    env:
      - HF_TOKEN=xxx
      - MODEL_ID=Qwen/Qwen-VL-Chat
    expose:
      - port: 8080
        to:
          - service: frontend

profiles:
  compute:
    frontend:
      cpu: 1
      memory: '2Gi'
      storage: '2Gi'

    ai_models_gpu:
      cpu: 8
      memory: '40Gi'
      storage: '50Gi'
      gpu:
        units: 1
        attributes:
          vendor:
            nvidia:
              - model: a100
  placement:
    dcloud:
      pricing:
        frontend:
          denom: uakt
          amount: 10
        ai_models_gpu:
          denom: uakt
          amount: 10000

deployment:
  frontend:
    dcloud:
      profile: frontend
      count: 1
  sketch-to-image:
    dcloud:
      profile: ai_models_gpu
      count: 1
  text-to-image:
    dcloud:
      profile: ai_models_gpu
      count: 1
  image-editor:
    dcloud:
      profile: ai_models_gpu
      count: 1
