
version: "2.0"

services:
  frontend:
    image: node:20
    command:
      - "npm"
      - "run"
      - "start"
    env:
      - "PORT=80"
      - "HOST=0.0.0.0"
      # Environment variables to connect to the other agentic services
      - "AKASH_CHAT_API_KEY=xxx"
      - "HF_TOKEN=xxx"
      - "SKETCH_TO_IMAGE_URL=http://sketch-to-image:8080"
      - "TEXT_TO_IMAGE_URL=http://text-to-image:8080"
      - "IMAGE_EDITOR_URL=http://image-editor:8080"
    expose:
      - port: 80
        as: 80
        to:
          - global: true

  sketch-to-image:
    image: vllm/vllm-openai:latest
    command: ["bash", "-c"]
    args:
      - "vllm serve gokaygokay/Sketch-to-Image-Kontext-Dev-LoRA"
    env:
      - "HF_TOKEN=xxx"
    expose:
      - port: 8080
        to:
          - service: frontend

  text-to-image:
    image: vllm/vllm-openai:latest
    command: ["bash", "-c"]
    args:
      - "vllm serve lodestones/Chroma"
    env:
      - "HF_TOKEN=xxx"
    expose:
      - port: 8080
        to:
          - service: frontend

  image-editor:
    image: vllm/vllm-openai:latest
    command: ["bash", "-c"]
    args:
      - "vllm serve Qwen/Qwen-Image-Edit"
    env:
      - "HF_TOKEN=xxx"
    expose:
      - port: 8080
        to:
          - service: frontend

profiles:
  compute:
    frontend:
      cpu: 1
      memory: "2Gi"
      storage: "2Gi"

    ai_models_gpu:
      cpu: 8
      memory: "32Gi"
      storage: "50Gi"
      gpu:
        units: 1
        attributes:
          vendor:
            nvidia:
              - model: rtx4090

  placement:
    dcloud:
      pricing:
        frontend:
          denom: uakt
          amount: 10
        ai_models_gpu:
          denom: uakt
          amount: 100

deployment:
  frontend:
    dcloud:
      profile: frontend
      count: 1

  sketch-to-image:
    dcloud:
      profile: ai_models_gpu
      count: 1

  text-to-image:
    dcloud:
      profile: ai_models_gpu
      count: 1

  image-editor:
    dcloud:
      profile: ai_models_gpu
      count: 1
